USE [master]
GO

/****** Object:  Database [SIMPLE_ERP]    Script Date: 7/11/2019 10:00:06 PM ******/
CREATE DATABASE [SIMPLE_ERP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SIMPLE_ERP', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\SIMPLE_ERP.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SIMPLE_ERP_log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\SIMPLE_ERP_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SIMPLE_ERP] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SIMPLE_ERP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SIMPLE_ERP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET ANSI_NULLS ON 
GO

ALTER DATABASE [SIMPLE_ERP] SET ANSI_PADDING ON 
GO

ALTER DATABASE [SIMPLE_ERP] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [SIMPLE_ERP] SET ARITHABORT ON 
GO

ALTER DATABASE [SIMPLE_ERP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SIMPLE_ERP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SIMPLE_ERP] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [SIMPLE_ERP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [SIMPLE_ERP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SIMPLE_ERP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SIMPLE_ERP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SIMPLE_ERP] SET  MULTI_USER 
GO

ALTER DATABASE [SIMPLE_ERP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SIMPLE_ERP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SIMPLE_ERP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SIMPLE_ERP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SIMPLE_ERP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SIMPLE_ERP] SET QUERY_STORE = OFF
GO

USE [SIMPLE_ERP]
GO

EXEC [SIMPLE_ERP].sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SIMPLE_ERP 2016 Sample OLTP Database' 
GO

USE [master]
GO

ALTER DATABASE [SIMPLE_ERP] SET  READ_WRITE 
GO

USE [SIMPLE_ERP]
GO